---
- name: System update for Silverblue
  hosts: all
  become: true
  tasks:
    - name: Update system packages
      command: rpm-ostree upgrade
      register: update_result
      changed_when: "'No upgrades available' not in update_result.stdout"

    - name: Check if reboot is needed
      command: rpm-ostree status --json
      register: ostree_status
      changed_when: false

    - name: Reboot if needed
      reboot:
        msg: "Rebooting to apply system updates"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: "'\"booted\": false' in ostree_status.stdout"