---
- name: System update
  hosts: all
  become: true
  
  vars:
    static_whitelist:
      - root
      - daemon
      - bin
      - sys
      - sync
      - games
      - man
      - lp
      - mail
      - news
      - uucp
      - proxy
      - www-data
      - backup
      - list
      - irc
      - gnats
      - nobody
      - systemd-network
      - systemd-resolve
      - syslog
      - messagebus
      - _apt
      - lxd
      - uuidd
      - dnsmasq

  tasks:
    - name: Get list of users with UID >= 1000
      command: "awk -F: '$3 >= 1000 { print $1 }' /etc/passwd"
      register: user_list_raw

    - name: Set full whitelist including client[0-9]+ and client
      set_fact:
      whitelist: "{{ static_whitelist + (user_list_raw.stdout_lines | select('match', '^client[0-9]+$') | list) + ['client'] }}"

    - name: Build filtered user list (excluding whitelisted users)
      set_fact:
        users_to_delete: "{{ user_list_raw.stdout_lines | difference(whitelist) }}"

    - name: Delete non-whitelisted users
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      loop: "{{ users_to_delete }}"
      when: users_to_delete | length > 0

    - name: Stopping IP-block service
      ansible.builtin.systemd:
        name: resolve_and_block.service
        state: stopped

    - name: Flush all IPv4 iptables rules
      ansible.builtin.shell: |
        iptables -F
        iptables -X
        iptables -t nat -F
        iptables -t nat -X
        iptables -t mangle -F
        iptables -t mangle -X

    - name: Flush IPv6 rules and set default policy to DROP
      ansible.builtin.shell: |
        ip6tables -F
        ip6tables -X
        ip6tables -t mangle -F
        ip6tables -t mangle -X

    - name: empty whole whitelist
      ansible.builtin.copy:
        dest: "/etc/unbound/unbound.conf.d/whitelist.conf"
        content: ""
        mode: '0644'

    - name: restart unbound
      ansible.builtin.systemd:
        name: unbound
        state: restarted
    
    - name: Unload the deny-all AppArmor profile temporarily
      ansible.builtin.command:
        cmd: apparmor_parser -R /etc/apparmor.d/custom-list

    - name: Updating packages
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
        update_cache: yes

    - name: Restarting system and restoring system functionality...
      ansible.builtin.reboot:
        reboot_timeout: 600

      