- name: Create low-privileged user with home directory and add to 'students' group
  hosts: all
  become: true
  vars_files:
    - user_data.json
  tasks:
    - name: Ensure the 'students' group exists
      ansible.builtin.group:
        name: students
        state: present

    - name: Ensure the user exists and is added to 'students' group
      ansible.builtin.user:
        name: "{{ item.username }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
        create_home: yes
        home: "/var/home/{{ item.username }}"
        groups: students
        setype: user_home_dir_t
      loop: "{{ users }}"
      loop_control:
        loop_var: item

    - name: Create standard directories
      ansible.builtin.file:
        path: "/var/home/{{ item.username }}/{{ item.dir }}"
        state: directory
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: '0755'
        setype: user_home_t
      loop: "{{ users | product(['Desktop', 'Documents', 'Downloads', 'Music', 'Pictures', 'Videos']) | list }}"
      loop_control:
        label: "Creating {{ item.1 }} for {{ item.0.username }}"