- name: delete user
  hosts: all
  become: true
  tasks:
  
    - name: update system1
      ansible.builtin.command: sudo apt update -y

    - name: update system2
      ansible.builtin.command: sudo apt upgrade -y

    - name: install openssh-server
      ansible.builtin.command: sudo apt install openssh-server -y

    - name: install curl
      ansible.builtin.command: sudo apt install curl -y

    - name: add pi-hole
      ansible.builtin.command: curl -sSL https://install.pi-hole.net | bash