- name: delete user
  hosts: all
  become: yes
  tasks:
  
    - name: update system
      ansible.builtin.command: sudo apt update && sudo apt upgrade -y

    - name: install openssh-server
      ansible.builtin.command: sudo apt install openssh-server -y

    - name: install curl
      ansible.builtin.command: sudo apt install curl -y

    - name: add pi-hole
      ansible.builtin.command: curl -sSL https://install.pi-hole.net | bash