- name: delete user
  hosts: all
  become: true
  vars_files:
    - user_data.json
  
  tasks:
    - name: delete user
      ansible.builtin.user:
        name: "{{ item.username }}"
        state: absent
        remove: yes
      loop: "{{ users }}"
      loop_control:
        loop_var: item
  