---
- name: configure unbound whitelist
  hosts: all
  vars_files:
    - allowed_domains.json
  tasks:
    - name: Ensure config file exists
      ansible.builtin.file:
        path: "/etc/unbound/unbound.conf.d/whitelist.conf"
        state: touch
        mode: '0644'
      
    - name: write default settings to file
      ansible.builtin.lineinfile:
        path: "/etc/unbound/unbound.conf.d/whitelist.conf"
        line: "{{ item }}"
        create: yes
      with_items:
      - "server:"
      - "  local-zone: \".\" refuse"
    
    - name: write allowed domains to file
      ansible.builtin.lineinfile:
        path: "/etc/unbound/unbound.conf.d/whitelist.conf"
        line: "  local-zone: \"{{ item }}\" transparent"
        create: yes
      with_items: "{{ domains }}"

    - name: restart service
      ansible.builtin.systemd:
        name: unbound
        state: restarted
