---
- name: clear domains except blacklist
  hosts: all
  become: true
  tasks:
    - name: empty whole whitelist
      ansible.builtin.copy:
        dest: "/etc/unbound/unbound.conf.d/whitelist.conf"
        content: ""
        mode: '0644'

    - name: write default settings to file
      ansible.builtin.lineinfile:
        path: "/etc/unbound/unbound.conf.d/whitelist.conf"
        line: "{{ item }}"
        create: yes
      with_items:
      - "server:"
      - "  local-zone: \".\" refuse"

    - name: restart unbound
      ansible.builtin.systemd:
        name: unbound
        state: restarted