- name: Create low-privileged user with home directory
  hosts: all
  become: yes
  vars_files:
    - user_data.yml
  tasks:
    - name: Ensure the user exists
      ansible.builtin.user:
        name: "{{ item.username }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
        create_home: yes
      loop: "{{ users }}"
      loop_control:
        loop_var: item

    - name: Create default directories for each user
      ansible.builtin.file:
        path: "/home/{{ item.username }}/{{ directory }}"
        state: directory
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: '0755'
      loop: "{{ users }}"
      loop_control:
        loop_var: item
      vars:
        directories:
          - Desktop
          - Documents
          - Downloads
          - Music
          - Pictures
          - Videos
      with_items: "{{ directories }}"
