- name: Create low-privileged user with home directory
  hosts: all
  become: yes
  vars:
    username: test
    user_password: "{{ 'test' | password_hash('sha512') }}"
  tasks:
    - name: Ensure the user exists
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ user_password }}"
        shell: /bin/bash
        state: present
        create_home: yes

    - name: Create default directories in the user's home
      ansible.builtin.file:
        path: "/home/{{ username }}/{{ item }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0755'
      loop:
        - Desktop
        - Documents
        - Downloads
        - Music
        - Pictures
        - Videos
