- name: Add computer
  hosts: all
  become: true
  tasks:

    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes

    - name: Install required packages
      apt:
        name:
          - unbound
          - apparmor
          - apparmor-utils
        state: present

    - name: Enable and start Unbound service
      systemd:
        name: unbound
        enabled: yes
        state: started

    - name: Enable and start AppArmor service
      systemd:
        name: apparmor
        enabled: yes
        state: started
