---
- name: Copy SSH key to remote client
  hosts: all
  gather_facts: no
  vars_prompt:
    - name: "client_ip"
      prompt: "Enter the client server IP address"
      private: no

    - name: "ansible_user"
      prompt: "Enter the SSH username for the client server"
      private: no

  tasks:
    - name: Add SSH key to remote user's authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
      vars:
        ansible_host: "{{ client_ip }}"
