---
- name: Copy SSH key to remote Silverblue client
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: "/var/home/{{ ansible_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      
    - name: Add SSH key to remote user's authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
        path: "/var/home/{{ ansible_user }}/.ssh/authorized_keys"
        manage_dir: yes
        
    - name: Set SELinux context using semanage
      command: semanage fcontext -a -t ssh_home_t "/var/home/{{ ansible_user }}/.ssh(/.*)?"
      ignore_errors: yes

    - name: Apply SELinux context using restorecon
      command: restorecon -Rv "/var/home/{{ ansible_user }}/.ssh"
      ignore_errors: yes