- name: Create AppArmor profiles from whitelist.json
  hosts: all
  become: yes
  vars_files:
    - whitelist.json
  tasks:
    - name: Debug whitelist variable
      debug:
        msg: "whitelist variable loaded: {{ whitelist }}"

    - name: Copy AppArmor profiles
      copy:
        dest: "/etc/apparmor.d/usr.bin.{{ item.app_name }}"
        content: "{{ item.profile }}"
      loop: "{{ whitelist }}"
      loop_control:
        loop_var: item

    - name: Load AppArmor profile
      command: "apparmor_parser -r /etc/apparmor.d/usr.bin.{{ item.app_name }}"
      loop: "{{ whitelist }}"
      loop_control:
        loop_var: item

    - name: Enforce AppArmor profile
      command: "aa-enforce /etc/apparmor.d/usr.bin.{{ item.app_name }}"
      loop: "{{ whitelist }}"
      loop_control:
        loop_var: item
