- name: Create AppArmor deny-all blacklist
  hosts: all
  become: yes
  tasks:
    - name: Create deny-all AppArmor profile
      copy:
        dest: /etc/apparmor.d/custom.deny-all
        content: |
          #include <tunables/global>
          
          /usr/bin/* {
            deny /** rwklx,
          }

    - name: Load the deny-all AppArmor profile
      command: apparmor_parser -r /etc/apparmor.d/custom.deny-all

    - name: Enforce the deny-all profile
      command: aa-enforce /etc/apparmor.d/custom.deny-all
