- name: Remove AppArmor whitelisted profiles from whitelist.json
  hosts: all
  become: yes
  vars_files:
    - whitelist.json
  tasks:
    - name: Delete profile files
      file:
        path: "/etc/apparmor.d/custom-list{{ item.name }}"
        state: absent
      loop: "{{ whitelist }}"
