- name: Create AppArmor profiles from whitelist.json
  hosts: all
  become: yes
  vars_files:
    - whitelist.json
  tasks:

    - name: Check if whitelist.json exists
      stat:
        path: "{{ whitelist_file }}"
      register: whitelist_file_stat

    - name: Fail if whitelist.json doesn't exist
      fail:
        msg: "whitelist.json not found"
      when: not whitelist_file_stat.stat.exists

    - name: Copy AppArmor profiles
      copy:
        dest: "/etc/apparmor.d/usr.bin.{{ item.name }}"
        content: "{{ item.profile }}"
      loop: "{{ whitelist }}"

    - name: Load AppArmor profile
      command: "apparmor_parser -r /etc/apparmor.d/usr.bin.{{ item.name }}"
      loop: "{{ whitelist }}"

    - name: Enforce AppArmor profile
      command: "aa-enforce /etc/apparmor.d/usr.bin.{{ item.name }}"
      loop: "{{ whitelist }}"
