---
- name: Apply SELinux policy based on blacklist.json
  hosts: all
  become: true
  vars_files:
    - blacklist.json

  tasks:
    - name: Create SELinux policy file
      ansible.builtin.copy:
        dest: "/tmp/block_apps.te"
        content: |
          module block_apps 1.0;

          require {
              class process { execmem execstack };
              type sudo_t;  # sudo context for sudo users
          }

          {% for app in blacklist %}
          # Block the application {{ app }} for all users
          deny {{ app | basename }}_exec_t:process { execmem execstack };

          # Allow users in the sudo group to execute the application
          allow sudo_t {{ app | basename }}_exec_t:process { execmem execstack };
          {% endfor %}

        mode: '0644'

    - name: Compile and apply SELinux policy
      command: "semodule -i /tmp/block_apps.pp"
      when: ansible_facts['selinux']['status'] == 'enabled'

    - name: Clean up temporary SELinux policy file
      file:
        path: /tmp/block_apps.te
        state: absent

    - name: Clean up temporary SELinux policy file after compilation
      file:
        path: /tmp/block_apps.pp
        state: absent
