---
- name: configure unbound whitelist
  hosts: all
  become: true
  vars_files:
    - allowed_domains.json

  tasks:
    - name: Ensure unbound config directory exists
      ansible.builtin.file:
        path: /etc/unbound/conf.d
        state: directory
        mode: '0755'

    - name: Ensure config file exists
      ansible.builtin.file:
        path: /etc/unbound/conf.d/whitelist.conf
        state: touch
        mode: '0644'

    - name: Write default settings to file
      ansible.builtin.lineinfile:
        path: /etc/unbound/conf.d/whitelist.conf
        line: "{{ item }}"
        create: yes
        state: present
      loop:
        - "server:"
        - "  local-zone: \".\" refuse"

    - name: Write allowed domains to file
      ansible.builtin.lineinfile:
        path: /etc/unbound/conf.d/whitelist.conf
        line: "  local-zone: \"{{ item }}\" transparent"
        create: yes
        state: present
      loop: "{{ domains }}"

    - name: Restart unbound service
      ansible.builtin.systemd:
        name: unbound
        state: restarted
        enabled: true
